name: subduelOfDragon
version: '1.1'
main: si.f5.stsaria.subduelOfDragon.SubDuelOfDragon
api-version: '1.21'
author: stsaria
website: https://github.com/stsaria/subduelOfDragon

commands:
  up:
    description: Upgrade Equipment
    permission: subduer
  copy:
    description: Copy item
    permission: subduer
  setcon:
    description: Set configure for adjustment game balance
    permission: admin
  getcons:
    description: Get configures
    permission: subduer
  sethome:
    description: Set player home for teleport
    permission: subduer
  home:
    description: teleport home
    permission: subduer
  getsaves:
    description: Get saves
    permission: admin
  savedragon:
    description: Save config and save data
    permission: admin
  ok:
    description: OK with teleporting there and setting the spawn point
    permission: subduer
permissions:
  subduer:
    description: Subduer of Dragon
    default: true
  admin:
    description: Admin
    default: op